-- https://github.com/spring-projects/spring-batch/tree/master/spring-batch-core/src/main/resources/org/springframework/batch/core

-- Autogenerated: do not edit this file
DROP TABLE  IF EXISTS batch.STEP_EXECUTION_CONTEXT;
DROP TABLE  IF EXISTS batch.JOB_EXECUTION_CONTEXT;
DROP TABLE  IF EXISTS batch.STEP_EXECUTION;
DROP TABLE  IF EXISTS batch.JOB_EXECUTION_PARAMS;
DROP TABLE  IF EXISTS batch.JOB_EXECUTION;
DROP TABLE  IF EXISTS batch.JOB_INSTANCE;

DROP SEQUENCE  IF EXISTS batch.STEP_EXECUTION_SEQ ;
DROP SEQUENCE  IF EXISTS batch.JOB_EXECUTION_SEQ ;
DROP SEQUENCE  IF EXISTS batch.JOB_SEQ ;
