package eu.daiad.web.model.error;

public enum UserErrorCode implements ErrorCode {
	ROLE_INITIALIZATION,
	ADMIN_INITIALIZATION,
	USERNANE_RESERVED,
	USERNANE_NOT_AVAILABLE,
	USERNANE_NOT_FOUND,
	WHITELIST_MISMATCH,
	USERNAME_EXISTS_IN_WHITELIST,
	NO_ROLE_SELECTED,
	ROLE_NOT_FOUND,
	UTILITY_DOES_NOT_EXIST,
	USER_ID_NOT_FOUND,
	USER_KEY_NOT_FOUND,
	ACCOUNT_ACCESS_RESTRICTED,
	PASSWORD_RESET_APPLICATION_NOT_SUPPORTED,
	PASSWORD_RESET_NOT_ALLOWED,
	PASSWORD_RESET_TOKEN_NOT_FOUND,
	PASSWORD_RESET_TOKEN_EXPIRED,
	PASSWORD_RESET_TOKEN_ALREADY_REEDEMED,
	PASSWORD_RESET_TOKEN_USER_NOT_FOUND,
	PASSWORD_RESET_PIN_MISMATCH;

	@Override
	public String getMessageKey() {
		return (this.getClass().getSimpleName() + '.' + this.name());
	}
}
